### ISSUE TITLE
AttributeError: 'GradientObserver' object has no attribute '_create_slots'

### ISSUE THREAD

**Issue by adam-hartshorne** [pedro-r-marques/keras-opt#2]
This works with the tensorflow 2.0 (beta), but it appears changes have been made to the api and it now fails with tensorflow-nightly with the following message,

  File "...\keras\optimizer_v2\optimizer_v2.py", line 539, in __getattribute__
    return super(OptimizerV2, self).__getattribute__(name)
AttributeError: 'GradientObserver' object has no attribute '_create_slots'
