### PR TITLE
Move to the new Optimizer v2 API in TF 2.0.

### LINKED ISSUE #2: AttributeError: 'GradientObserver' object has no attribute '_create_slots'
This works with the tensorflow 2.0 (beta), but it appears changes have been made to the api and it now fails with tensorflow-nightly with the following message,

  File "...\keras\optimizer_v2\optimizer_v2.py", line 539, in __getattribute__
    return super(OptimizerV2, self).__getattribute__(name)
AttributeError: 'GradientObserver' object has no attribute '_create_slots'

### PR DESCRIPTION
**Pull request by pedro-r-marques**
The Optimiser V2 API no longer works based on modifying the graph via the get_updates method. Instead gradients can be observed and then applied by the optimiser. This should probably allow one to write a simpler implementation / API; but for now do the simplest work possible.

Closes #2

### CODE REVIEW

**Comment by AakashKumarNain** [comment]
@pedro-r-marques  I ran into the same issue. Can you please give an example?

**Comment by pedro-r-marques** [comment]
> @pedro-r-marques I ran into the same issue. Can you please give an example?

@AakashKumarNain This PR move the code to the TF 2.0 API (OptimizerV2).
Did you bump into issues after this PR merged ?

Would it be possible to execute the unit tests in the package ? And let me know if there are errors being raised. Please create a GitHub Issue with the errors that you see.

It would really help to know the exact version of TF that you are using.

**Comment by AakashKumarNain** [comment]
@pedro-r-marques I am on `rc0` and I was trying to implement a new Optimizer and I got the same error: `object has no attribute '_create_slots'`

I will file a detailed issue on the same

**Comment by pedro-r-marques** [comment]
@AakashKumarNain 
Thanks for the explanation. The Optimiser API changed significantly around the TF 2.0 GradientTape concept. Perhaps you can follow the diffs in this commit as an example of what you need to change.
